apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-color
  template:
    metadata:
      labels:
        app: nginx-color
    spec:
      containers:
        - name: nginx-color
          image: kubedevio/nginx-color:green